/**
 * Astrocartography Line Interpretations
 * Based on classical astrocartography principles
 *
 * Rich interpretations for each planet/line type combination
 * covering career, love, health, home, wellbeing, and wealth influences.
 */

import type { Planet } from '@/lib/astro-types';
import type { LineInterpretation } from './types';

type LineType = 'ASC' | 'DSC' | 'MC' | 'IC';

// Complete interpretation database based on classical astrocartography
export const LINE_INTERPRETATIONS: Record<Planet, Record<LineType, LineInterpretation>> = {
  Sun: {
    ASC: {
      planet: 'Sun',
      lineType: 'ASC',
      title: 'Sun on the Ascendant',
      shortDescription: 'Strong vitality, charisma, and magnetism. You naturally radiate confidence and attract recognition here.',
      themes: ['Leadership', 'Vitality', 'Self-expression', 'Confidence', 'Recognition'],
      careers: ['Executive roles', 'Entertainment', 'Politics', 'Entrepreneurship', 'Public speaking'],
      challenges: ['Ego conflicts', 'Burnout from visibility', 'Overconfidence in health'],
      opportunities: ['Natural leadership roles', 'Personal magnetism brings opportunities', 'Health improvements', 'Building personal brand'],
      bestFor: ['Career advancement', 'Gaining confidence', 'Health recovery'],
      rating: 5,
    },
    DSC: {
      planet: 'Sun',
      lineType: 'DSC',
      title: 'Sun on the Descendant',
      shortDescription: 'Attracts confident, successful partners who support your goals. Power-couple dynamics and mutual respect flourish.',
      themes: ['Partnership', 'Mutual respect', 'Successful partners', 'Collaboration'],
      careers: ['Consulting', 'Diplomatic roles', 'Partnership businesses', 'Marriage counseling'],
      challenges: ['Attracting ego-driven partners', 'Power dynamics in relationships'],
      opportunities: ['Meeting influential people', 'Supportive partnerships', 'Business collaborations'],
      bestFor: ['Finding a partner', 'Power-couple dynamics', 'Business partnerships'],
      rating: 4,
    },
    MC: {
      planet: 'Sun',
      lineType: 'MC',
      title: 'Sun on the Midheaven',
      shortDescription: 'Leadership, recognition, and public success. Personal success brings financial and professional reward.',
      themes: ['Career success', 'Public recognition', 'Leadership', 'Authority', 'Achievement'],
      careers: ['CEO', 'Industry leader', 'Government official', 'Celebrity', 'Executive'],
      challenges: ['Workaholism', 'Public scrutiny', 'Work-life imbalance'],
      opportunities: ['Major career breakthroughs', 'Industry leadership', 'Fame and recognition'],
      bestFor: ['Career peak', 'Professional authority', 'Public recognition'],
      rating: 5,
    },
    IC: {
      planet: 'Sun',
      lineType: 'IC',
      title: 'Sun on the Imum Coeli',
      shortDescription: 'Core vitality foundation. Sunny, warm, proud family home with strong inner strength.',
      themes: ['Home pride', 'Family foundation', 'Inner strength', 'Vitality base'],
      careers: ['Real estate', 'Family business', 'Home-based leadership'],
      challenges: ['Career may feel secondary', 'Family obligations'],
      opportunities: ['Strong family bonds', 'Real estate success', 'Inner peace'],
      bestFor: ['Establishing roots', 'Family time', 'Building foundation'],
      rating: 4,
    },
  },
  Moon: {
    ASC: {
      planet: 'Moon',
      lineType: 'ASC',
      title: 'Moon on the Ascendant',
      shortDescription: 'Emotional well-being supports physical health. Sensitive but nurturing energy with strong intuition.',
      themes: ['Emotions', 'Intuition', 'Nurturing', 'Public appeal', 'Sensitivity'],
      careers: ['Caregiving', 'Hospitality', 'Real estate', 'Food industry', 'Healthcare'],
      challenges: ['Emotional overwhelm', 'Mood swings', 'Oversensitivity', 'Absorbing others emotions'],
      opportunities: ['Deep emotional connections', 'Popularity with public', 'Intuitive insights', 'Feeling cared for'],
      bestFor: ['Emotional healing', 'Connecting with people', 'Starting a family'],
      rating: 4,
    },
    DSC: {
      planet: 'Moon',
      lineType: 'DSC',
      title: 'Moon on the Descendant',
      shortDescription: 'Emotionally connected, nurturing relationships. Deep bonds with caring, family-oriented partners.',
      themes: ['Emotional partnerships', 'Nurturing relationships', 'Deep bonding', 'Family-oriented love'],
      careers: ['Couples therapy', 'Wedding planning', 'Family counseling'],
      challenges: ['Emotional dependency', 'Codependent bonds', 'Attracting needy partners'],
      opportunities: ['Deep emotional bonds', 'Finding a caring partner', 'Family expansion'],
      bestFor: ['Romantic relationships', 'Marriage', 'Emotional partnerships'],
      rating: 4,
    },
    MC: {
      planet: 'Moon',
      lineType: 'MC',
      title: 'Moon on the Midheaven',
      shortDescription: 'Career tied to emotions and caregiving. Success through nurturing others or appealing to public emotions.',
      themes: ['Public nurturing', 'Popularity', 'Caregiving career', 'Women in business'],
      careers: ['Healthcare', 'Real estate', 'Food industry', 'Childcare', 'Public relations'],
      challenges: ['Emotional exposure publicly', 'Career fluctuations with moods'],
      opportunities: ['Popular appeal', 'Success in nurturing fields', 'Connection with women'],
      bestFor: ['Caring professions', 'Public-facing roles', 'Real estate careers'],
      rating: 4,
    },
    IC: {
      planet: 'Moon',
      lineType: 'IC',
      title: 'Moon on the Imum Coeli',
      shortDescription: 'Warm, nurturing, family-centered home. Deep emotional safety and high comfort. Ideal for raising children.',
      themes: ['Home comfort', 'Family bonds', 'Emotional security', 'Ancestral connection', 'Belonging'],
      careers: ['Home-based business', 'Family care', 'Ancestry research'],
      challenges: ['Difficulty leaving home', 'Over-attachment to past', 'Comfort-seeking'],
      opportunities: ['Creating ideal home', 'Family healing', 'Emotional grounding', 'Digestive health'],
      bestFor: ['Settling down', 'Raising family', 'Emotional healing'],
      rating: 5,
    },
  },
  Mercury: {
    ASC: {
      planet: 'Mercury',
      lineType: 'ASC',
      title: 'Mercury on the Ascendant',
      shortDescription: 'Communication skills enhanced for advancement. Mental agility, learning, and networking flourish here.',
      themes: ['Communication', 'Learning', 'Writing', 'Mental agility', 'Networking'],
      careers: ['Writing', 'Teaching', 'Journalism', 'Sales', 'Translation', 'Marketing'],
      challenges: ['Mental restlessness', 'Scattered focus', 'Overthinking'],
      opportunities: ['Learning new skills', 'Writing success', 'Business communication'],
      bestFor: ['Education', 'Writing projects', 'Communication careers'],
      rating: 4,
    },
    DSC: {
      planet: 'Mercury',
      lineType: 'DSC',
      title: 'Mercury on the Descendant',
      shortDescription: 'Intellectual partnerships and witty connections. Business partnerships and trade agreements thrive.',
      themes: ['Intellectual bonds', 'Business partnerships', 'Trade', 'Negotiations'],
      careers: ['Business consulting', 'Literary agents', 'Contract negotiation', 'Trade partnerships'],
      challenges: ['Partners who overthink', 'Communication issues in relationships'],
      opportunities: ['Intellectual partnerships', 'Business deals', 'Contract success'],
      bestFor: ['Business partnerships', 'Legal matters', 'Negotiations'],
      rating: 3,
    },
    MC: {
      planet: 'Mercury',
      lineType: 'MC',
      title: 'Mercury on the Midheaven',
      shortDescription: 'Communication careers, teaching, and writing. Success through ideas, media, and commerce.',
      themes: ['Communication career', 'Teaching', 'Writing', 'Commerce', 'Technology'],
      careers: ['Author', 'Teacher', 'Journalist', 'Tech industry', 'Marketing executive'],
      challenges: ['Career restlessness', 'Juggling multiple projects'],
      opportunities: ['Publishing success', 'Teaching positions', 'Business acumen', 'Financial skills'],
      bestFor: ['Media careers', 'Education', 'Writing/publishing'],
      rating: 4,
    },
    IC: {
      planet: 'Mercury',
      lineType: 'IC',
      title: 'Mercury on the Imum Coeli',
      shortDescription: 'Communication-rich, intellectual home. Great for home offices, studying, and family discussions.',
      themes: ['Home office', 'Family communication', 'Learning at home', 'Siblings'],
      careers: ['Remote work', 'Home tutoring', 'Writing from home'],
      challenges: ['Mental restlessness at home', 'Too many home projects'],
      opportunities: ['Home-based learning', 'Family discussions', 'Local connections'],
      bestFor: ['Home office', 'Studying', 'Remote work'],
      rating: 3,
    },
  },
  Venus: {
    ASC: {
      planet: 'Venus',
      lineType: 'ASC',
      title: 'Venus on the Ascendant',
      shortDescription: 'High physical attractiveness and romantic ease. Money attraction through charm. Beauty, pleasure, and art flourish.',
      themes: ['Attractiveness', 'Charm', 'Beauty', 'Romance', 'Pleasure', 'Art'],
      careers: ['Art', 'Fashion', 'Beauty industry', 'Hospitality', 'Design', 'Diplomacy'],
      challenges: ['Overindulgence', 'Vanity', 'Laziness', 'Ignoring deeper issues'],
      opportunities: ['Finding love', 'Artistic success', 'Beauty enhancement', 'Money through charm'],
      bestFor: ['Romance', 'Art projects', 'Beauty/fashion careers', 'Spa vacations'],
      rating: 5,
    },
    DSC: {
      planet: 'Venus',
      lineType: 'DSC',
      title: 'Venus on the Descendant',
      shortDescription: 'The primary love line. Romantic attraction, marriage, and harmonious partnerships. Shared resources and marriage benefits.',
      themes: ['Romance', 'Marriage', 'Harmonious love', 'Artistic partnerships', 'Shared resources'],
      careers: ['Wedding industry', 'Art partnerships', 'Couples work', 'Beauty collaborations'],
      challenges: ['Idealizing partners', 'Avoiding conflict', 'Codependency', 'Too comfortable'],
      opportunities: ['Meeting soulmate', 'Beautiful partnerships', 'Artistic collaborations', 'Financial partnership luck'],
      bestFor: ['Marriage', 'Romance', 'Dating', 'Artistic partnerships'],
      rating: 5,
    },
    MC: {
      planet: 'Venus',
      lineType: 'MC',
      title: 'Venus on the Midheaven',
      shortDescription: 'Artistic careers, beauty, hospitality, and diplomacy. Success through charm, aesthetic appeal, and social grace.',
      themes: ['Artistic career', 'Beauty industry', 'Diplomacy', 'Social success', 'Charm'],
      careers: ['Artist', 'Designer', 'Diplomat', 'Influencer', 'Curator', 'PR specialist'],
      challenges: ['Relying too much on charm', 'Lacking aggressive business instinct'],
      opportunities: ['Art world success', 'Beauty industry leadership', 'Diplomatic roles', 'Social climbing'],
      bestFor: ['Creative careers', 'Fashion/beauty', 'Hospitality'],
      rating: 5,
    },
    IC: {
      planet: 'Venus',
      lineType: 'IC',
      title: 'Venus on the Imum Coeli',
      shortDescription: 'Beautiful, harmonious, artistic home. Physical comfort, family harmony, and valuable properties. Ideal for healing spaces.',
      themes: ['Beautiful home', 'Family harmony', 'Inherited beauty', 'Comfort', 'Aesthetics'],
      careers: ['Interior design', 'Home decor', 'Family art business', 'Real estate'],
      challenges: ['Over-spending on home', 'Staying too comfortable'],
      opportunities: ['Creating beautiful space', 'Family harmony', 'Valuable property', 'Sanctuary creation'],
      bestFor: ['Home beautification', 'Vacation homes', 'Retirement', 'Healing spaces'],
      rating: 5,
    },
  },
  Mars: {
    ASC: {
      planet: 'Mars',
      lineType: 'ASC',
      title: 'Mars on the Ascendant',
      shortDescription: 'Athletic ability, physical strength, and stamina. Assertiveness and drive in work. Sexual attractiveness and confidence.',
      themes: ['Physical energy', 'Assertiveness', 'Athletics', 'Courage', 'Sexual confidence'],
      careers: ['Athletics', 'Military', 'Surgery', 'Firefighting', 'Entrepreneurship', 'Fitness'],
      challenges: ['Aggression', 'Accidents', 'Inflammation', 'Burnout', 'Impatience'],
      opportunities: ['Athletic achievements', 'Bold ventures', 'Physical transformation', 'Strong earning power'],
      bestFor: ['Sports', 'Starting businesses', 'Physical challenges', 'Intense fitness'],
      rating: 4,
    },
    DSC: {
      planet: 'Mars',
      lineType: 'DSC',
      title: 'Mars on the Descendant',
      shortDescription: 'Passionate, sexually attractive connections. Dynamic partnerships with active energy. May include healthy competition.',
      themes: ['Passionate love', 'Sexual attraction', 'Active partnerships', 'Dynamic bonds'],
      careers: ['Sports partnerships', 'Competitive teams', 'Active collaborations'],
      challenges: ['Relationship conflicts', 'Attracting aggressive people', 'Arguments', 'Power struggles'],
      opportunities: ['Passionate romance', 'Dynamic business partners', 'Athletic teams', 'Healthy sexuality'],
      bestFor: ['Passionate relationships', 'Sports teams', 'Active couples'],
      rating: 3,
    },
    MC: {
      planet: 'Mars',
      lineType: 'MC',
      title: 'Mars on the Midheaven',
      shortDescription: 'Competitive careers and action-oriented fields. Ambitious earnings and competitive advantage. Fast growth potential.',
      themes: ['Career ambition', 'Competition', 'Leadership', 'Achievement', 'Action'],
      careers: ['CEO', 'Military officer', 'Surgeon', 'Professional athlete', 'Entrepreneur', 'Sales'],
      challenges: ['Work conflicts', 'High stress', 'Burnout risk', 'Being seen as aggressive'],
      opportunities: ['Rapid career advancement', 'Competitive success', 'Leadership roles', 'Ambitious earnings'],
      bestFor: ['Career advancement', 'Competitive fields', 'Startups', 'Fast growth'],
      rating: 4,
    },
    IC: {
      planet: 'Mars',
      lineType: 'IC',
      title: 'Mars on the Imum Coeli',
      shortDescription: 'Active home life with family activity. Good for home renovation but potential for family conflicts or domestic stress.',
      themes: ['Active home', 'Home renovation', 'Family dynamics', 'Physical foundation'],
      careers: ['Home renovation', 'Family fitness', 'Home-based athletics'],
      challenges: ['Family conflicts', 'Restlessness at home', 'Domestic accidents', 'Noise'],
      opportunities: ['Home improvement', 'Family activities', 'House flipping', 'Active foundation'],
      bestFor: ['Home renovation', 'Active family life', 'Flipping houses'],
      rating: 3,
    },
  },
  Jupiter: {
    ASC: {
      planet: 'Jupiter',
      lineType: 'ASC',
      title: 'Jupiter on the Ascendant',
      shortDescription: 'Optimism and luck in opportunities. Health luck and wellness advantages. Everything expands here.',
      themes: ['Luck', 'Expansion', 'Optimism', 'Wisdom', 'Travel', 'Growth'],
      careers: ['Higher education', 'Publishing', 'International business', 'Law', 'Philosophy'],
      challenges: ['Over-expansion', 'Weight gain', 'Overconfidence', 'Digestive overindulgence'],
      opportunities: ['Educational success', 'International opportunities', 'Spiritual growth', 'Stress relief'],
      bestFor: ['Education', 'Spiritual growth', 'Starting ventures', 'Wellness retreats'],
      rating: 5,
    },
    DSC: {
      planet: 'Jupiter',
      lineType: 'DSC',
      title: 'Jupiter on the Descendant',
      shortDescription: 'Lucky, supportive, open relationships. Partners want to help you. Financial partnership luck and generous connections.',
      themes: ['Beneficial partnerships', 'Generosity', 'International love', 'Supportive partners'],
      careers: ['International partnerships', 'Educational collaborations', 'Legal partnerships'],
      challenges: ['Partners who over-promise', 'Over-trusting', 'Naïveté in partnerships'],
      opportunities: ['Lucky partnerships', 'International connections', 'Generous lovers', 'Helpful people'],
      bestFor: ['Business partnerships', 'International marriage', 'Meeting helpful people'],
      rating: 5,
    },
    MC: {
      planet: 'Jupiter',
      lineType: 'MC',
      title: 'Jupiter on the Midheaven',
      shortDescription: 'Luck, expansion, and visibility in career. The ultimate career line for professional opportunities and recognition.',
      themes: ['Career expansion', 'Professional luck', 'International career', 'Abundance'],
      careers: ['Professor', 'Judge', 'International executive', 'Publisher', 'Philosopher'],
      challenges: ['Over-promising', 'Career excess', 'Reckless expansion'],
      opportunities: ['Major career success', 'International recognition', 'Effortless career growth'],
      bestFor: ['Career expansion', 'Academic work', 'International business', 'Networking'],
      rating: 5,
    },
    IC: {
      planet: 'Jupiter',
      lineType: 'IC',
      title: 'Jupiter on the Imum Coeli',
      shortDescription: 'Spacious, lucky, expanding home. Large real estate at better prices. Family support and lucky property investments.',
      themes: ['Home expansion', 'Family blessings', 'Spacious living', 'Cultural roots', 'Abundance'],
      careers: ['Real estate investment', 'Family business expansion', 'Home hospitality'],
      challenges: ['Overspending on property', 'Too much focus on family'],
      opportunities: ['Real estate luck', 'Family expansion', 'Lucky inheritance', 'Property deals'],
      bestFor: ['Buying property', 'Expanding home', 'Starting a family'],
      rating: 5,
    },
  },
  Saturn: {
    ASC: {
      planet: 'Saturn',
      lineType: 'ASC',
      title: 'Saturn on the Ascendant',
      shortDescription: 'Discipline and maturity stabilize emotions. Slow progress but lasting achievement. May feel heavier or tired initially.',
      themes: ['Responsibility', 'Structure', 'Maturity', 'Discipline', 'Long-term building'],
      careers: ['Management', 'Government', 'Engineering', 'Architecture', 'Finance'],
      challenges: ['Depression', 'Low energy', 'Chronic issues', 'Joint/bone problems', 'Isolation'],
      opportunities: ['Building lasting structures', 'Respect through hard work', 'Career discipline'],
      bestFor: ['Serious work', 'Long-term projects', 'Building foundations', 'Health discipline'],
      rating: 3,
    },
    DSC: {
      planet: 'Saturn',
      lineType: 'DSC',
      title: 'Saturn on the Descendant',
      shortDescription: 'Serious, committed, long-term bonds. Relationships may feel heavy but offer stability. Serious financial responsibility in partnerships.',
      themes: ['Commitment', 'Serious relationships', 'Long-term bonds', 'Karmic partners'],
      careers: ['Business consulting', 'Contract law', 'Long-term partnerships'],
      challenges: ['Relationships feel heavy', 'Attracting critical partners', 'Loneliness', 'Obligation'],
      opportunities: ['Lasting commitments', 'Marriage stability', 'Karmic relationships', 'Stable families'],
      bestFor: ['Long-term commitments', 'Marriage', 'Business contracts'],
      rating: 3,
    },
    MC: {
      planet: 'Saturn',
      lineType: 'MC',
      title: 'Saturn on the Midheaven',
      shortDescription: 'Discipline and achievement through hard work. Slow but solid career climb. Steady responsibility builds authority over time.',
      themes: ['Career authority', 'Professional reputation', 'Long-term success', 'Hard work'],
      careers: ['CEO', 'Government official', 'Architect', 'Financial advisor', 'Senior manager'],
      challenges: ['Slow progress', 'Career delays', 'Heavy work burden', 'Feels frustrating'],
      opportunities: ['Lasting reputation', 'Authority positions', 'Respect through work'],
      bestFor: ['Building career legacy', 'Government/admin jobs', 'Long-term institutions'],
      rating: 4,
    },
    IC: {
      planet: 'Saturn',
      lineType: 'IC',
      title: 'Saturn on the Imum Coeli',
      shortDescription: 'Structured, traditional, solid family property. Grounded, anchored feeling good for permanent settlement. Long-term wealth building.',
      themes: ['Family structure', 'Property building', 'Traditional home', 'Ancestral karma'],
      careers: ['Family business structure', 'Real estate management', 'Land ownership'],
      challenges: ['Heavy family responsibility', 'Traditional expectations', 'Chronic foundational issues'],
      opportunities: ['Building solid home', 'Land ownership', 'Ancestral property', 'Permanent roots'],
      bestFor: ['Buying land', 'Settling down', 'Long-term family wealth'],
      rating: 3,
    },
  },
  Uranus: {
    ASC: {
      planet: 'Uranus',
      lineType: 'ASC',
      title: 'Uranus on the Ascendant',
      shortDescription: 'Innovation, freedom, and sudden change. Freedom from restrictive patterns. Erratic but liberating energy.',
      themes: ['Innovation', 'Freedom', 'Awakening', 'Originality', 'Rebellion'],
      careers: ['Technology', 'Science', 'Astrology', 'Invention', 'Activism'],
      challenges: ['Erratic health', 'Sudden illness/recovery', 'Nervous system issues', 'Alienation'],
      opportunities: ['Breakthrough moments', 'Finding your tribe', 'Unconventional healing'],
      bestFor: ['Tech ventures', 'Finding authentic self', 'Alternative medicine'],
      rating: 3,
    },
    DSC: {
      planet: 'Uranus',
      lineType: 'DSC',
      title: 'Uranus on the Descendant',
      shortDescription: 'Unconventional relationships and sudden changes. Freedom within partnership. May feel unpredictable but exciting.',
      themes: ['Unconventional love', 'Freedom in partnership', 'Sudden connections', 'Unique bonds'],
      careers: ['Tech partnerships', 'Alternative healing teams', 'Open collaborations'],
      challenges: ['Instability', 'Commitment issues', 'Sudden breakups', 'Unpredictability'],
      opportunities: ['Meeting unique people', 'Freedom in love', 'Open relationships'],
      bestFor: ['Unconventional partnerships', 'Tech collaborations', 'Unique dynamics'],
      rating: 3,
    },
    MC: {
      planet: 'Uranus',
      lineType: 'MC',
      title: 'Uranus on the Midheaven',
      shortDescription: 'Innovation, technology, and unconventional career paths. Sudden career changes and breakthrough innovations.',
      themes: ['Innovation', 'Tech career', 'Unconventional success', 'Sudden changes'],
      careers: ['Tech entrepreneur', 'Scientist', 'Astrologer', 'Activist', 'Inventor'],
      challenges: ['Career instability', 'Controversial reputation', 'Sudden disruptions'],
      opportunities: ['Breakthrough innovations', 'Sudden success', 'Tech leadership'],
      bestFor: ['Tech careers', 'Innovation', 'Personal evolution'],
      rating: 4,
    },
    IC: {
      planet: 'Uranus',
      lineType: 'IC',
      title: 'Uranus on the Imum Coeli',
      shortDescription: 'Frequent moves and unconventional home setup. Unstable but liberating. Good for temporary setups or living flexibly.',
      themes: ['Unconventional home', 'Freedom at home', 'Smart home', 'Frequent moves'],
      careers: ['Remote tech work', 'Home innovation', 'Alternative living'],
      challenges: ['Home instability', 'Frequent relocations', 'Rootlessness', 'Can\'t settle'],
      opportunities: ['Creating unique home', 'Tech at home', 'Breaking family patterns'],
      bestFor: ['Temporary setups', 'Living flexibly', 'Breaking traditions'],
      rating: 2,
    },
  },
  Neptune: {
    ASC: {
      planet: 'Neptune',
      lineType: 'ASC',
      title: 'Neptune on the Ascendant',
      shortDescription: 'Spirituality, imagination, and peace. Spiritual healing and meditation flow easily. Enhanced intuition but clarity needed.',
      themes: ['Spirituality', 'Creativity', 'Intuition', 'Dreams', 'Healing', 'Compassion'],
      careers: ['Art', 'Music', 'Healing', 'Film', 'Photography', 'Spiritual work'],
      challenges: ['Confusion', 'Psychosomatic issues', 'Escapism', 'Boundary issues', 'Unclear health'],
      opportunities: ['Spiritual awakening', 'Artistic inspiration', 'Psychic development', 'Energy work'],
      bestFor: ['Spiritual retreats', 'Creative work', 'Yoga/meditation'],
      rating: 4,
    },
    DSC: {
      planet: 'Neptune',
      lineType: 'DSC',
      title: 'Neptune on the Descendant',
      shortDescription: 'Spiritual soulmate connections. Transcendent love with psychic connection. Risk of idealization or deception.',
      themes: ['Soulmate connections', 'Spiritual partnerships', 'Transcendent love', 'Psychic bonds'],
      careers: ['Spiritual counseling', 'Art collaborations', 'Healing partnerships'],
      challenges: ['Idealization', 'Deceptive partners', 'Codependency', 'Illusions in love'],
      opportunities: ['Soulmate connection', 'Spiritual partnership', 'Meditation couples'],
      bestFor: ['Spiritual partnerships', 'Creative collaboration', 'Psychic connection'],
      rating: 3,
    },
    MC: {
      planet: 'Neptune',
      lineType: 'MC',
      title: 'Neptune on the Midheaven',
      shortDescription: 'Creative/spiritual careers but clarity needed. Confusion about direction possible. Glamour and healing professions.',
      themes: ['Creative career', 'Spiritual vocation', 'Glamour', 'Healing profession', 'Arts'],
      careers: ['Artist', 'Musician', 'Healer', 'Actor', 'Spiritual teacher', 'Filmmaker'],
      challenges: ['Career confusion', 'Unclear reputation', 'Direction uncertainty'],
      opportunities: ['Creative success', 'Spiritual calling', 'Healing profession'],
      bestFor: ['Arts career', 'Spiritual work', 'Healing professions'],
      rating: 3,
    },
    IC: {
      planet: 'Neptune',
      lineType: 'IC',
      title: 'Neptune on the Imum Coeli',
      shortDescription: 'Spiritual home and healing sanctuary. Dream-like environment near water. Unclear boundaries need attention.',
      themes: ['Spiritual home', 'Ancestral mysteries', 'Waterfront living', 'Healing sanctuary'],
      careers: ['Home-based healing', 'Spiritual practice at home', 'Creative studio'],
      challenges: ['Family secrets', 'Unclear boundaries', 'Escapism at home', 'Unstable foundation'],
      opportunities: ['Spiritual sanctuary', 'Creative home', 'Meditation retreat'],
      bestFor: ['Spiritual retreat', 'Living near water', 'Healing centers'],
      rating: 3,
    },
  },
  Pluto: {
    ASC: {
      planet: 'Pluto',
      lineType: 'ASC',
      title: 'Pluto on the Ascendant',
      shortDescription: 'Deep transformation and personal power. Cellular/ancestral healing. Intense but empowering energy.',
      themes: ['Transformation', 'Power', 'Rebirth', 'Intensity', 'Psychology'],
      careers: ['Psychology', 'Research', 'Investigation', 'Surgery', 'Wealth management'],
      challenges: ['Power struggles', 'Obsession', 'Control issues', 'Intensity'],
      opportunities: ['Deep transformation', 'Personal power', 'Psychological insight', 'Empowerment'],
      bestFor: ['Personal transformation', 'Power positions', 'Deep healing'],
      rating: 4,
    },
    DSC: {
      planet: 'Pluto',
      lineType: 'DSC',
      title: 'Pluto on the Descendant',
      shortDescription: 'Intense, transformative relationships. Deep soul-level bonds but power dynamics and intensity. Financial control issues possible.',
      themes: ['Transformative love', 'Deep bonds', 'Power dynamics', 'Soul connections'],
      careers: ['Therapy partnerships', 'Research teams', 'Investment partnerships'],
      challenges: ['Controlling partners', 'Jealousy', 'Power struggles', 'Financial control issues'],
      opportunities: ['Deep transformation through others', 'Soul bonds', 'Powerful alliances'],
      bestFor: ['Deep relationships', 'Joint ventures', 'Transformative partnerships'],
      rating: 3,
    },
    MC: {
      planet: 'Pluto',
      lineType: 'MC',
      title: 'Pluto on the Midheaven',
      shortDescription: 'Transformation, power, and influential positions. Control over financial resources. Intense career transformations.',
      themes: ['Career power', 'Influence', 'Transformation', 'Strategic control'],
      careers: ['CEO', 'Psychologist', 'Researcher', 'Investor', 'Surgeon', 'Strategist'],
      challenges: ['Power struggles at work', 'Career crises', 'Controversy'],
      opportunities: ['Industry transformation', 'Powerful career', 'Deep impact', 'Resource control'],
      bestFor: ['Power positions', 'Research', 'High-stakes business'],
      rating: 4,
    },
    IC: {
      planet: 'Pluto',
      lineType: 'IC',
      title: 'Pluto on the Imum Coeli',
      shortDescription: 'Deep ancestral healing and family transformation. Property transformation and hidden inheritance. Power dynamics at home.',
      themes: ['Family transformation', 'Ancestral power', 'Deep roots', 'Hidden wealth'],
      careers: ['Family therapy', 'Genealogy research', 'Estate management'],
      challenges: ['Family power struggles', 'Ancestral trauma', 'Control at home'],
      opportunities: ['Family healing', 'Property transformation', 'Hidden inheritance', 'Powerful foundations'],
      bestFor: ['Ancestral healing', 'Family transformation', 'Property investment'],
      rating: 3,
    },
  },
  Chiron: {
    ASC: {
      planet: 'Chiron',
      lineType: 'ASC',
      title: 'Chiron on the Ascendant',
      shortDescription: 'Excellent for therapy, rehab, and finding right healers. Your wounds become wisdom. Healing location for recovery.',
      themes: ['Healing', 'Wisdom', 'Teaching', 'Vulnerability', 'Mentorship'],
      careers: ['Healer', 'Therapist', 'Teacher', 'Coach', 'Alternative medicine'],
      challenges: ['Old wounds surfacing', 'Feeling inadequate', 'Slow healing'],
      opportunities: ['Becoming a healer', 'Teaching from experience', 'Finding right healers', 'Self-healing'],
      bestFor: ['Rehab centers', 'Therapy retreats', 'Healing travel', 'Recovery'],
      rating: 4,
    },
    DSC: {
      planet: 'Chiron',
      lineType: 'DSC',
      title: 'Chiron on the Descendant',
      shortDescription: 'Healing through relationships. Partners may be healers or trigger important healing. Therapeutic partnerships.',
      themes: ['Healing relationships', 'Therapeutic partnerships', 'Wounded healers'],
      careers: ['Couples therapy', 'Healing partnerships', 'Mentoring relationships'],
      challenges: ['Attracting wounded people', 'Relationship wounds', 'Healing others first'],
      opportunities: ['Healing through partnership', 'Finding a healer partner', 'Teaching couples'],
      bestFor: ['Relationship healing', 'Finding a healer', 'Therapeutic work'],
      rating: 3,
    },
    MC: {
      planet: 'Chiron',
      lineType: 'MC',
      title: 'Chiron on the Midheaven',
      shortDescription: 'Career in healing or teaching. Your wounds inform your professional calling. Mentorship and wisdom-sharing.',
      themes: ['Healing career', 'Teaching vocation', 'Wounded healer', 'Mentorship'],
      careers: ['Therapist', 'Teacher', 'Healer', 'Coach', 'Alternative practitioner'],
      challenges: ['Career wounds', 'Imposter syndrome', 'Professional vulnerability'],
      opportunities: ['Becoming a teacher/healer', 'Career from wounds', 'Mentoring others'],
      bestFor: ['Healing professions', 'Teaching', 'Coaching'],
      rating: 4,
    },
    IC: {
      planet: 'Chiron',
      lineType: 'IC',
      title: 'Chiron on the Imum Coeli',
      shortDescription: 'Family healing and ancestral wounds come up for resolution. Home as healing sanctuary. Inner wisdom development.',
      themes: ['Family healing', 'Ancestral wounds', 'Home sanctuary', 'Inner healing'],
      careers: ['Family therapy', 'Home-based healing', 'Ancestral work'],
      challenges: ['Family wounds', 'Childhood pain resurfaces', 'Feeling homeless'],
      opportunities: ['Healing family patterns', 'Creating healing home', 'Ancestral wisdom'],
      bestFor: ['Family healing', 'Inner work', 'Creating sanctuary'],
      rating: 3,
    },
  },
  NorthNode: {
    ASC: {
      planet: 'NorthNode',
      lineType: 'ASC',
      title: 'North Node on the Ascendant',
      shortDescription: 'Destiny path activated. Growth into higher self. Life purpose and personal evolution unfold here.',
      themes: ['Destiny', 'Soul growth', 'Life purpose', 'Personal evolution'],
      careers: ['Following your calling', 'Purpose-driven work', 'Authentic expression'],
      challenges: ['Comfort zone pushing', 'Uncertainty', 'Growing pains'],
      opportunities: ['Living your purpose', 'Soul evolution', 'Authentic self-expression'],
      bestFor: ['Finding purpose', 'Personal growth', 'Destiny activation'],
      rating: 5,
    },
    DSC: {
      planet: 'NorthNode',
      lineType: 'DSC',
      title: 'North Node on the Descendant',
      shortDescription: 'Partnerships are your growth edge. Karmic relationships help you evolve. Finding your people.',
      themes: ['Karmic relationships', 'Growth through others', 'Destined partnerships'],
      careers: ['Partnership-based growth', 'Collaborative purpose', 'Relationship coaching'],
      challenges: ['Dependency lessons', 'Relationship challenges', 'Balancing self and other'],
      opportunities: ['Karmic partnerships', 'Growth through relationships', 'Finding your people'],
      bestFor: ['Finding life partner', 'Karmic relationships', 'Collaborative growth'],
      rating: 4,
    },
    MC: {
      planet: 'NorthNode',
      lineType: 'MC',
      title: 'North Node on the Midheaven',
      shortDescription: 'Career is your destiny. Professional purpose and public calling. Vocational fulfillment awaits.',
      themes: ['Career destiny', 'Professional calling', 'Public purpose', 'Vocational growth'],
      careers: ['Purpose-driven career', 'Calling fulfillment', 'Public service'],
      challenges: ['Career pressure', 'Public responsibility', 'Finding true calling'],
      opportunities: ['Fulfilling career purpose', 'Public recognition', 'Vocational calling'],
      bestFor: ['Career destiny', 'Finding calling', 'Purpose-driven work'],
      rating: 5,
    },
    IC: {
      planet: 'NorthNode',
      lineType: 'IC',
      title: 'North Node on the Imum Coeli',
      shortDescription: 'Home and family are your growth area. Building roots is part of your destiny. Ancestral purpose.',
      themes: ['Family destiny', 'Building foundations', 'Home growth', 'Ancestral purpose'],
      careers: ['Family-oriented purpose', 'Home-based calling', 'Ancestral work'],
      challenges: ['Settling down', 'Family responsibilities', 'Inner work'],
      opportunities: ['Building meaningful home', 'Family purpose', 'Ancestral healing'],
      bestFor: ['Settling down', 'Starting family', 'Building foundations'],
      rating: 4,
    },
  },
};

/**
 * Life category rankings based on classical astrocartography
 *
 * CAREER: Jupiter MC > Sun MC > Mercury MC > Mars MC > Saturn MC
 * LOVE: Venus DSC > Sun DSC > Jupiter DSC > Mars DSC > Neptune DSC
 * HEALTH: Sun ASC > Jupiter ASC > Venus IC > Mars ASC > Moon IC
 * HOME: Venus IC > Moon IC > Jupiter IC > Saturn IC > Sun IC
 * WELLBEING: Venus lines > Jupiter lines > Moon lines > Neptune ASC > Pluto ASC
 * WEALTH: Jupiter lines > Venus lines > Sun MC > Saturn IC > Mercury MC
 */

/**
 * Get the interpretation for a specific planet and line type
 */
export function getLineInterpretation(
  planet: Planet,
  lineType: LineType
): LineInterpretation | null {
  return LINE_INTERPRETATIONS[planet]?.[lineType] || null;
}

/**
 * Get a brief one-liner for a line
 */
export function getLineOneLiner(planet: Planet, lineType: LineType): string {
  const interp = getLineInterpretation(planet, lineType);
  return interp?.shortDescription || `${planet} ${lineType} line`;
}

/**
 * Get top themes for a line
 */
export function getLineThemes(planet: Planet, lineType: LineType): string[] {
  const interp = getLineInterpretation(planet, lineType);
  return interp?.themes || [];
}

/**
 * Get the best lines for a specific life category
 */
export function getBestLinesForCategory(category: 'career' | 'love' | 'health' | 'home' | 'wellbeing' | 'wealth'): Array<{ planet: Planet; lineType: LineType }> {
  switch (category) {
    case 'career':
      return [
        { planet: 'Jupiter', lineType: 'MC' },
        { planet: 'Sun', lineType: 'MC' },
        { planet: 'Mercury', lineType: 'MC' },
        { planet: 'Mars', lineType: 'MC' },
        { planet: 'Saturn', lineType: 'MC' },
      ];
    case 'love':
      return [
        { planet: 'Venus', lineType: 'DSC' },
        { planet: 'Sun', lineType: 'DSC' },
        { planet: 'Jupiter', lineType: 'DSC' },
        { planet: 'Mars', lineType: 'DSC' },
        { planet: 'Moon', lineType: 'DSC' },
      ];
    case 'health':
      return [
        { planet: 'Sun', lineType: 'ASC' },
        { planet: 'Jupiter', lineType: 'ASC' },
        { planet: 'Venus', lineType: 'IC' },
        { planet: 'Mars', lineType: 'ASC' },
        { planet: 'Moon', lineType: 'IC' },
      ];
    case 'home':
      return [
        { planet: 'Venus', lineType: 'IC' },
        { planet: 'Moon', lineType: 'IC' },
        { planet: 'Jupiter', lineType: 'IC' },
        { planet: 'Saturn', lineType: 'IC' },
        { planet: 'Sun', lineType: 'IC' },
      ];
    case 'wellbeing':
      return [
        { planet: 'Venus', lineType: 'ASC' },
        { planet: 'Jupiter', lineType: 'ASC' },
        { planet: 'Moon', lineType: 'IC' },
        { planet: 'Neptune', lineType: 'ASC' },
        { planet: 'Pluto', lineType: 'ASC' },
      ];
    case 'wealth':
      return [
        { planet: 'Jupiter', lineType: 'MC' },
        { planet: 'Venus', lineType: 'ASC' },
        { planet: 'Sun', lineType: 'MC' },
        { planet: 'Saturn', lineType: 'IC' },
        { planet: 'Mercury', lineType: 'MC' },
      ];
    default:
      return [];
  }
}
