/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_globepoint_lat: (a: number) => number;
export const __wbg_get_globepoint_lng: (a: number) => number;
export const __wbg_get_planetaryposition_ecliptic_longitude: (a: number) => number;
export const __wbg_get_planetaryposition_planet: (a: number) => number;
export const __wbg_globepoint_free: (a: number, b: number) => void;
export const __wbg_planetaryposition_free: (a: number, b: number) => void;
export const __wbg_set_globepoint_lat: (a: number, b: number) => void;
export const __wbg_set_globepoint_lng: (a: number, b: number) => void;
export const __wbg_set_planetaryposition_ecliptic_longitude: (a: number, b: number) => void;
export const __wbg_set_planetaryposition_planet: (a: number, b: number) => void;
export const calculate_all_lines: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const calculate_all_lines_local: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => any;
export const calculate_delta_t: (a: number, b: number) => number;
export const calculate_gmst: (a: number) => number;
export const calculate_horizon_latitude: (a: number, b: number, c: number, d: number) => [number, number];
export const calculate_ic_longitude: (a: number, b: number) => number;
export const calculate_local_space_lines: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => any;
export const calculate_mc_longitude: (a: number, b: number) => number;
export const calculate_natal_chart: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => any;
export const calculate_planetary_position: (a: number, b: number) => number;
export const get_timezone_from_coords: (a: number, b: number) => [number, number];
export const get_timezone_offset_hours: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const globepoint_new: (a: number, b: number) => number;
export const is_rising: (a: number, b: number, c: number) => number;
export const local_to_utc_julian_date: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const planetaryposition_new: (a: number, b: number, c: number, d: number) => number;
export const to_julian_date: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const ut_to_tt: (a: number, b: number, c: number) => number;
export const calculate_lst: (a: number, b: number) => number;
export const __wbg_set_planetaryposition_declination: (a: number, b: number) => void;
export const __wbg_set_planetaryposition_right_ascension: (a: number, b: number) => void;
export const __wbg_get_planetaryposition_declination: (a: number) => number;
export const __wbg_get_planetaryposition_right_ascension: (a: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
